echo ria>last_news.txt
echo rambler>>last_news.txt
echo rbc>>last_news.txt
echo bbc>>last_news.txt
echo gazeta>>last_news.txt
echo economics>>last_news.txt
echo internet>>last_news.txt
echo sport>>last_news.txt
echo science>>last_news.txt
echo culture>>last_news.txt